version: '3.7'

services:
  mysql:
    build: ./back-end/mysql_service/
    container_name: MySQL
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tchipa
      MYSQL_USER: ybenlafk
      MYSQL_PASSWORD: ybenlafk123
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - tchipa
  nestjs-app:
    build: ./back-end/
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      DATABASE_URL: "mysql://ybenlafk:ybenlafk123@mysql:3306/tchipa"
    networks: 
      - tchipa
  nextjs-app:
    build: ./front-end/
    ports:
      - "3000:3000"
    depends_on:
      - nestjs-app
    environment:
      NODE_ENV: development
    networks:
      - tchipa

networks:
  tchipa:
    driver: bridge