import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {NavBar} from '../app/components'  // Import your NavBar component

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CourseCrafter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Include your head content here */}
      </head>
      <body className={inter.className}>
        <div className="flex">
          <NavBar />
            <div className="flex-grow mt-10 p-10">{children}</div>
        </div>
      </body>
    </html>
  )
}
