USE tchipa;

GRANT ALL PRIVILEGES ON tchipa.* TO 'ybenlafk'@'%' WITH GRANT OPTION;
GRANT CREATE, ALTER, DROP, INDEX, INSERT, SELECT, UPDATE, DELETE, CREATE TEMPORARY TABLES, LOCK TABLES ON *.* TO 'ybenlafk'@'%';
FLUSH PRIVILEGES;
